### ISSUE TITLE
Formatting of `tool_version` value for `blastx` tool in `snp_calling` process

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/fluviewer-nf#32]
The `tool_version` entry for the `blastx` tool in the `snp_calling` process looks like this:

```yaml
- process_name: snp_caling
  tools:
    - tool_name: blastx
      tool_version: blastx: 2.15.0+
```

...but it should look like this:

```yaml
- process_name: snp_caling
  tools:
    - tool_name: blastx
      tool_version: 2.15.0+
```
