### ISSUE TITLE
Add `genoflu_version` field to the GenoFLU tsv output

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/fluviewer-nf#47]
To assist with data provenance, add a `genoflu_version` field to the GenoFLU tsv output. This will help us to keep track of which results were generated with which version of GenoFLU over time.

This info is captured in the provenance for the `genoflu` process, but it would be simpler and more convenient for our data collection processes if it were included in each line of the GenoFLU output. This is especially helpful when aggregating many outputs that were collected from analyses that were run with different versions of GenoFLU.

```yaml
- process_name: genoflu
  tools:
    - tool_name: genoflu
      tool_version: 1.05
```
